---
- hosts: debian
  name: Update all hosts running Debian
  tasks:
    - name: update all Debian packages
      become: true
      apt:
        upgrade: dist
        update_cache: true
        autoclean: true
        autoremove: true
        cache_valid_time: 86400

    - name: check if reboot-require file exists
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: show if reboot is rquired
      debug:
        msg: "{{ inventory_hostname | reboot_needed }}"
      when: reboot_required.stat.exists
